import { api } from '../core/api.js';
import { store } from '../core/store.js';
import { $, $$, on, icon, esc, money, toMajor, dateFmt, ago, avatar, toast, modal, confirmBox, withBtn, btnHtml, fieldErrors, confetti, empty, currencies, animateNumbers } from '../core/ui.js';
import { nav } from '../app.js';

const ROLES = { owner: 'Owner', partner: 'Partner', investor: 'Investor', accountant: 'Accountant (view-only)' };
const TYPES = { investment: ['💰', 'Investment', 'good'], profit: ['📈', 'Profit', 'good'], expense: ['🧾', 'Expense', 'bad'], withdrawal: ['🏧', 'Withdrawal', 'warn'] };
const idBadge = (s) => ({ approved: '<span class="badge good">NID verified</span>', pending: '<span class="badge warn">NID in review</span>', rejected: '<span class="badge bad">NID rejected</span>', missing: '<span class="badge bad">NID missing</span>' }[s] || '');

export const nidFields = () => `<div class="secure-note">${icon('lock')}<span>Your NID is <b>encrypted</b> and shown masked everywhere. Only authorised compliance staff can review it — each view is logged. One NID can link to one account.</span></div>
  <div class="form-grid two"><div class="field"><label>NID number</label><input class="input mono" name="nidNumber" inputmode="numeric" autocomplete="off" placeholder="10, 13 or 17 digits" maxlength="20"></div><div class="field"><label>Date of birth</label><input class="input" type="date" name="dob"></div></div>
  <div class="field"><label>Full name (exactly as on NID)</label><input class="input" name="nameOnNid" autocomplete="off"></div>
  <div class="form-grid two"><div class="field"><label>Father’s name (optional)</label><input class="input" name="fatherName"></div><div class="field"><label>Address (optional)</label><input class="input" name="address"></div></div>
  <label class="check"><input type="checkbox" name="consent"><span>I confirm this is my own National ID and I consent to its verification.</span></label>`;
export function readNid(f) {
  if (!f.consent.checked) throw new Error('Please confirm the identity declaration');
  return { nidNumber: f.nidNumber.value, nameOnNid: f.nameOnNid.value, dob: f.dob.value, fatherName: f.fatherName.value, address: f.address.value };
}

// Shared by the invitations list and the invite landing page.
export function inviteAcceptForm(box, inv, hasNid, done) {
  box.innerHTML = `<form class="stack" id="af" style="text-align:left" novalidate>${inv.needsNid && !hasNid ? `<h4 style="margin:0">Verify your identity to join</h4>${nidFields()}` : ''}<div class="row wrap">${btnHtml('Accept invitation', 'btn-primary grow', 'type="submit"')}<button type="button" class="btn btn-glass" data-decline>Decline</button></div></form>`;
  $('#af', box).addEventListener('submit', async (e) => { e.preventDefault(); const f = e.target; fieldErrors(f);
    try { const body = inv.needsNid && !hasNid ? { nid: readNid(f) } : {}; const d = await withBtn($('button[type=submit]', f), () => api.post(`/invitations/${inv.id}/accept`, body)); confetti(); toast('Welcome aboard! 🎉', 'good'); done(d.link || '/dashboard'); }
    catch (err) { if (err.details) fieldErrors(f, Object.fromEntries(Object.entries(err.details).map(([k, v]) => [k.replace('nid.', ''), v]))); toast(err.message, 'bad'); } });
  box.querySelector('[data-decline]').addEventListener('click', async () => { await api.post(`/invitations/${inv.id}/decline`); toast('Invitation declined', 'info'); done('/dashboard'); });
}

export async function invitations() {
  const d = await api.get('/invitations');
  const html = `<div class="stack" style="gap:18px"><h2 style="margin:0">Invitations</h2>${d.needsVerification ? `<div class="card">${empty('📧', 'Verify your email', 'Invitations sent to your email appear here after verification.', '<a class="btn btn-gold" href="#/verify-email">Verify now</a>')}</div>` : d.invitations.length ? d.invitations.map((i) => `<div class="card" data-inv="${i.id}"><div class="row wrap"><span class="group-emoji">${i.kind === 'business' ? '🤝' : '🧳'}</span><div class="grow"><b>${esc(i.targetName)}</b><div class="muted">${esc(i.inviterName)} invited you${i.kind === 'business' ? ` as <b>${esc(i.role)}</b>${i.ownershipPercent ? ` · ${i.ownershipPercent}% share` : ''}` : ' to join the group'} · expires ${dateFmt(i.expiresAt)}</div></div><button class="btn btn-primary" data-open>Review</button></div><div class="inv-box" style="margin-top:16px"></div></div>`).join('') : `<div class="card">${empty('📭', 'No pending invitations', 'When someone invites you to a group or business, it will show up here.')}</div>`}</div>`;
  return { title: 'Invitations', html, mount(root) {
    on(root, 'click', '[data-open]', (_e, b) => { const card = b.closest('[data-inv]'); const inv = d.invitations.find((i) => i.id === card.dataset.inv); b.remove(); inviteAcceptForm($('.inv-box', card), inv, d.hasNid, (link) => nav(link)); });
  } };
}

// ───────────────────────── list ─────────────────────────
export async function list({ user }) {
  const [{ businesses }, { kyc }] = await Promise.all([api.get('/business'), api.get('/me/kyc')]);
  const html = `<div class="stack" style="gap:20px"><div class="row between wrap"><div><h2 style="margin:0">Business</h2><p class="muted" style="margin:0">Partnership ledgers with verified partners.</p></div><button class="btn btn-primary" id="new">${icon('plus')} New business</button></div>
  ${kyc ? `<div class="card tight row wrap">${icon('id')}<span class="grow">Identity on file: <b class="mono">${esc(kyc.masked)}</b> ${idBadge(kyc.status)}${kyc.status === 'rejected' ? ` — <span class="money-neg">${esc(kyc.reason || '')}</span>` : ''}</span>${kyc.status === 'rejected' ? '<a class="btn btn-gold sm" href="#/settings">Fix in Settings</a>' : ''}</div>` : ''}
  ${businesses.length ? `<div class="grid g3">${businesses.map((b) => `<a class="card hover group-card" href="#/business/${b.id}" style="text-decoration:none;color:inherit"><div class="row"><div class="group-emoji">🏢</div><div class="grow truncate"><b>${esc(b.name)}</b><div class="muted" style="font-size:.82rem">${esc(b.myRole)} · ${b.myOwnershipPercent}% · ${b.partnerCount} partners</div></div>${b.status === 'flagged' ? '<span class="badge bad">Review</span>' : ''}</div><div class="row between"><div><div class="faint" style="font-size:.72rem;font-weight:700">CASH POSITION</div><b class="mono">${money(b.cashPositionMinor, b.currency)}</b></div><div style="text-align:right"><div class="faint" style="font-size:.72rem;font-weight:700">NET PROFIT</div><b class="mono ${b.netProfitMinor >= 0 ? 'money-pos' : 'money-neg'}">${money(b.netProfitMinor, b.currency)}</b></div></div></a>`).join('')}</div>` : `<div class="card">${empty('🤝', 'No businesses yet', 'Create a business ledger and invite your partners by email. Everyone verifies with a National ID.', '<button class="btn btn-primary" data-new>Create a business</button>')}</div>`}</div>`;
  return { title: 'Business', html, mount(root) {
    const open = () => {
      const checks = [['Email verified', user.emailVerified, '#/verify-email'], ['Two-factor sign-in enabled', user.twoFactorEnabled, '#/settings']];
      if (!checks.every((c) => c[1])) return modal({ title: 'Before you start', body: `<p class="muted">For the safety of everyone’s money, business owners need:</p><div class="stack-sm">${checks.map(([t, ok, h]) => `<a href="${h}" class="ob-step ${ok ? 'done' : ''}" style="text-decoration:none;color:inherit"><span class="n">${ok ? '✓' : '!'}</span><b class="grow">${t}</b>${ok ? '' : icon('arrow')}</a>`).join('')}</div>` });
      modal({ title: 'Create a business', lg: true, body: `<form class="stack" id="bf" novalidate><div class="form-grid two"><div class="field"><label>Business name</label><input class="input" name="name" maxlength="100" required></div><div class="field"><label>Type</label><select class="input" name="type"><option value="partnership">Partnership</option><option value="sole">Sole proprietorship</option><option value="company">Company</option><option value="other">Other</option></select></div></div>
        <div class="form-grid two"><div class="field"><label>Currency</label><select class="input" name="currency">${Object.keys(currencies()).map((c) => `<option ${c === 'BDT' ? 'selected' : ''}>${c}</option>`).join('')}</select></div><div class="field"><label>Trade licence no. (optional)</label><input class="input" name="tradeLicense"></div></div>
        <div class="field"><label>Description</label><textarea class="input" name="description" maxlength="500" style="min-height:70px"></textarea></div><hr style="margin:4px 0"><h4 style="margin:0">Owner identity (NID)</h4>${kyc ? `<div class="secure-note">${icon('check')}<span>Using the identity on file: <b class="mono">${esc(kyc.masked)}</b> (${esc(kyc.status)}).</span></div>` : nidFields()}${btnHtml('Create business', 'btn-primary block lg', 'type="submit"')}</form>`,
      onMount: (m) => $('#bf', m.el).addEventListener('submit', async (e) => { e.preventDefault(); const f = e.target; fieldErrors(f);
        try { const body = { name: f.elements.name.value, type: f.type.value, currency: f.currency.value, tradeLicense: f.tradeLicense.value, description: f.description.value }; if (!kyc) body.nid = readNid(f);
          const d = await withBtn($('button[type=submit]', f), () => api.post('/business', body)); m.close(); confetti(); nav(`/business/${d.id}`); } catch (err) { if (err.details) fieldErrors(f, Object.fromEntries(Object.entries(err.details).map(([k, v]) => [k.replace('nid.', ''), v]))); toast(err.message, 'bad'); } }) });
    };
    root.addEventListener('click', (e) => { if (e.target.closest('#new') || e.target.closest('[data-new]')) open(); });
  } };
}

// ───────────────────────── detail ─────────────────────────
export async function detail({ params, user }) {
  let D = await api.get(`/business/${params.id}`); let tab = 'overview'; let txns = []; let tpage = 1; let tpages = 1; let tfilter = '';
  const owner = () => D.myRole === 'owner'; const writer = () => ['owner', 'partner'].includes(D.myRole); const cur = () => D.business.currency;
  const name = (id) => D.partners.find((p) => p.userId === id)?.name || 'Partner';
  const head = () => `<div class="card pad-lg glow"><div class="row wrap" style="gap:16px"><div class="group-emoji" style="width:64px;height:64px;font-size:2rem">🏢</div><div class="grow"><div class="row wrap" style="gap:8px"><h2 style="margin:0">${esc(D.business.name)}</h2>${D.business.status === 'flagged' ? '<span class="badge bad">Under review</span>' : '<span class="badge good">Active</span>'}</div><div class="muted">${esc(D.business.type)} · ${cur()} · you are <b>${esc(D.myRole)}</b></div></div>${writer() && D.business.status === 'active' ? `<button class="btn btn-primary" data-txn>${icon('plus')} Add entry</button>` : ''}</div>
    ${D.business.status === 'flagged' ? `<div class="tip" style="margin-top:14px">⚠️ This business is under compliance review${D.business.flagReason ? `: ${esc(D.business.flagReason)}` : ''}. New entries are paused.</div>` : ''}</div>
    <div class="tabs" id="tabs">${[['overview', 'chart', 'Overview'], ['ledger', 'receipt', 'Ledger'], ['partners', 'users', 'Partners'], ...(owner() ? [['audit', 'shield', 'Audit log']] : [])].map(([k, i, l]) => `<button class="tab ${tab === k ? 'on' : ''}" data-tab="${k}">${icon(i)}${l}</button>`).join('')}</div><div id="tb"></div>`;
  const S = () => D.summary;
  const overview = () => `<div class="stack" style="gap:16px"><div class="grid g4">${[['Investment', S().investment, ''], ['Profit', S().profit, 'money-pos'], ['Expenses', S().expense, 'money-neg'], ['Withdrawals', S().withdrawal, '']].map(([l, v, c]) => `<div class="card kpi"><span class="l">${l}</span><b class="v mono ${c}" data-count="${v}" data-cur="${cur()}">${money(0, cur())}</b></div>`).join('')}</div>
    <div class="grid g2"><div class="card glow"><div class="lbl">NET PROFIT</div><b class="mono ${S().netProfit >= 0 ? 'money-pos' : 'money-neg'}" style="font-size:2rem" data-count="${S().netProfit}" data-cur="${cur()}">${money(0, cur())}</b><hr><div class="lbl">CASH POSITION</div><b class="mono" style="font-size:1.4rem">${money(S().cashPosition, cur())}</b><p class="faint" style="font-size:.8rem;margin:6px 0 0">Investment + net profit − withdrawals</p></div>
    <div class="card"><h3>Profit share by ownership</h3>${D.profitShares.map((s) => { const p = D.partners.find((x) => x.userId === s.userId); return `<div class="list-item">${avatar(p, 'sm')}<div class="grow"><b>${esc(p?.name)}</b><div class="muted" style="font-size:.78rem">${p?.ownershipPercent}% ownership</div></div><b class="mono ${s.amountMinor > 0 ? 'money-pos' : ''}">${money(s.amountMinor, cur())}</b></div>`; }).join('') || '<p class="muted">No owners with a share yet.</p>'}</div></div>
    <div class="card"><h3>Partner contributions</h3>${D.partners.map((p) => { const b = S().byPartner[p.userId] || { investment: 0, profit: 0, expense: 0, withdrawal: 0 }; return `<div class="list-item">${avatar(p, 'sm')}<b class="grow">${esc(p.name)}</b><span class="muted mono" style="font-size:.85rem">invested ${money(b.investment, cur())}</span></div>`; }).join('')}</div></div>`;
  const ledger = () => `<div class="card"><div class="row wrap" style="margin-bottom:10px"><div class="pill-tabs" id="tf"><button class="chip ${tfilter ? '' : 'on'}" data-tf="">All</button>${Object.entries(TYPES).map(([k, [e, l]]) => `<button class="chip ${tfilter === k ? 'on' : ''}" data-tf="${k}">${e} ${l}</button>`).join('')}</div></div>
    ${txns.length ? txns.map((t) => `<div class="expense-row" style="cursor:default;${t.voided ? 'opacity:.5;text-decoration:line-through' : ''}"><div class="cat-ico">${TYPES[t.type][0]}</div><div class="grow truncate"><b>${TYPES[t.type][1]}${t.category ? ` · ${esc(t.category)}` : ''}</b><div class="muted truncate" style="font-size:.82rem">${esc(name(t.partner))} · ${dateFmt(t.date)}${t.note ? ` · ${esc(t.note)}` : ''}${t.voided ? ` · voided: ${esc(t.voidReason || '')}` : ''}</div></div><b class="mono ${t.type === 'profit' || t.type === 'investment' ? 'money-pos' : t.type === 'expense' ? 'money-neg' : ''}">${money(t.amountMinor, cur())}</b>${!t.voided && writer() && (owner() || t.createdBy === user.id) ? `<button class="btn btn-ghost sm" data-void="${t.id}" title="Void entry">${icon('x')}</button>` : ''}</div>`).join('') + (tpage < tpages ? '<button class="btn btn-glass block" data-more style="margin-top:12px">Load more</button>' : '') : empty('📒', 'No entries yet', 'Record investments, profits, expenses and withdrawals.')}<p class="faint" style="font-size:.8rem;margin:12px 0 0">🔒 The ledger is append-only: mistakes are voided with a reason, never deleted.</p></div>`;
  const partners = () => `<div class="grid g2"><div class="card"><div class="row between"><h3 style="margin:0">Partners</h3>${owner() ? `<button class="btn btn-primary sm" data-invite>${icon('plus')} Invite partner</button>` : ''}</div>
    ${D.partners.map((p) => `<div class="list-item">${avatar(p)}<div class="grow truncate"><b>${esc(p.name)}</b> ${p.userId === user.id ? '<span class="badge info">You</span>' : ''}<div class="muted truncate" style="font-size:.8rem">${esc(p.email || '')} · NID <span class="mono">${esc(p.identity.masked || '—')}</span></div></div><div style="text-align:right"><div><span class="badge">${esc(p.role)}</span> <b>${p.ownershipPercent}%</b></div><div style="margin-top:4px">${idBadge(p.identity.status)}</div></div>${owner() && p.userId !== user.id ? `<button class="btn btn-ghost sm" data-editp="${p.userId}">${icon('edit')}</button>` : ''}${p.userId === user.id && D.partners.length > 1 ? `<button class="btn btn-ghost sm" data-leave title="Leave">${icon('logout')}</button>` : ''}</div>`).join('')}</div>
    <div class="card"><h3>Pending invitations</h3>${D.invites.length ? D.invites.map((i) => `<div class="list-item"><span class="cat-ico">✉️</span><div class="grow truncate"><b class="truncate">${esc(i.email)}</b><div class="muted" style="font-size:.8rem">${esc(i.role)} · ${i.ownershipPercent}% · expires ${dateFmt(i.expiresAt)}</div></div>${owner() ? `<button class="btn btn-ghost sm" data-revoke="${i.id}">${icon('x')}</button>` : ''}</div>`).join('') : '<p class="muted">No pending invitations.</p>'}<div class="secure-note" style="margin-top:14px">${icon('shield')}<span>Invited partners must verify with a National ID before they can join.</span></div></div></div>`;
  async function loadTxns(reset = true) { if (reset) { tpage = 1; txns = []; } const d = await api.get(`/business/${D.business.id}/transactions?page=${tpage}&type=${tfilter}`); txns = reset ? d.transactions : [...txns, ...d.transactions]; tpages = d.pages; }
  const html = `<div class="stack" style="gap:20px" id="bd">${head()}</div>`;
  return { title: D.business.name, html, async mount(root) {
    const reload = async () => { D = await api.get(`/business/${D.business.id}`); await loadTxns(); $('#bd', root).innerHTML = head(); await paint(); };
    const paint = async () => { const tb = $('#tb', root); if (tab === 'overview') tb.innerHTML = overview(); else if (tab === 'ledger') tb.innerHTML = ledger(); else if (tab === 'partners') tb.innerHTML = partners(); else { const { events } = await api.get(`/business/${D.business.id}/audit`); tb.innerHTML = `<div class="card"><div class="timeline">${events.map((e) => `<div class="tl-item"><b>${esc(e.action)}</b> <span class="muted">by ${esc(e.actor || 'system')}</span><div class="faint" style="font-size:.78rem">${dateFmt(e.at, { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })}</div></div>`).join('')}</div></div>`; } animateNumbers(root); };
    await loadTxns(); await paint();
    on(root, 'click', '[data-tab]', async (_e, b) => { tab = b.dataset.tab; $$('#tabs .tab', root).forEach((t) => t.classList.toggle('on', t === b)); await paint(); });
    on(root, 'click', '[data-tf]', async (_e, b) => { tfilter = b.dataset.tf; await loadTxns(); await paint(); });
    on(root, 'click', '[data-more]', async () => { tpage += 1; await loadTxns(false); await paint(); });
    on(root, 'click', '[data-txn]', () => txnModal(D, user, reload));
    on(root, 'click', '[data-void]', (_e, b) => { modal({ title: 'Void entry', body: `<form class="stack" id="vf"><p class="muted" style="margin:0">Voided entries stay visible for audit but no longer count.</p><div class="field"><label>Reason</label><input class="input" name="reason" maxlength="200" required></div>${btnHtml('Void entry', 'btn-danger block', 'type="submit"')}</form>`, onMount: (m) => $('#vf', m.el).addEventListener('submit', async (e) => { e.preventDefault(); try { await api.post(`/business/${D.business.id}/transactions/${b.dataset.void}/void`, { reason: e.target.reason.value }); m.close(); toast('Entry voided', 'good'); reload(); } catch (err) { toast(err.message, 'bad'); } }) }); });
    on(root, 'click', '[data-invite]', () => invitePartnerModal(D, reload));
    on(root, 'click', '[data-revoke]', async (_e, b) => { await api.del(`/business/${D.business.id}/invites/${b.dataset.revoke}`); toast('Invitation revoked', 'good'); reload(); });
    on(root, 'click', '[data-editp]', (_e, b) => editPartnerModal(D, D.partners.find((p) => p.userId === b.dataset.editp), reload));
    on(root, 'click', '[data-leave]', async () => { if (!(await confirmBox({ title: 'Leave business?', text: 'Your ownership share returns to an owner.', ok: 'Leave', danger: true }))) return; try { await api.del(`/business/${D.business.id}/partners/${user.id}`); nav('/business'); } catch (e) { toast(e.message, 'bad'); } });
  } };
}

function txnModal(D, user, done) {
  const cur = D.business.currency;
  modal({ title: 'Add ledger entry', body: `<form class="stack" id="f" novalidate><div class="tabs" id="tt">${Object.entries(TYPES).map(([k, [e, l]], i) => `<button type="button" class="tab ${i ? '' : 'on'}" data-t="${k}" style="padding:9px 10px">${e} ${l}</button>`).join('')}</div>
    <div class="field"><label>Amount (${cur})</label><input class="input mono" name="amount" inputmode="decimal" style="font-size:1.3rem;font-weight:800" placeholder="0.00"></div>
    ${D.myRole === 'owner' && D.partners.length > 1 ? `<div class="field"><label>On behalf of</label><select class="input" name="partnerId">${D.partners.map((p) => `<option value="${p.userId}" ${p.userId === user.id ? 'selected' : ''}>${esc(p.name)}</option>`).join('')}</select></div>` : ''}
    <div class="form-grid two"><div class="field"><label>Category (optional)</label><input class="input" name="category" maxlength="40" placeholder="e.g. Inventory"></div><div class="field"><label>Date</label><input class="input" type="date" name="date" value="${new Date().toISOString().slice(0, 10)}"></div></div>
    <div class="field"><label>Note</label><input class="input" name="note" maxlength="300"></div>${btnHtml('Record entry', 'btn-primary block lg', 'type="submit"')}</form>`,
  onMount: (m) => { let type = 'investment'; on(m.el, 'click', '[data-t]', (_e, b) => { type = b.dataset.t; $$('#tt .tab', m.el).forEach((t) => t.classList.toggle('on', t === b)); });
    $('#f', m.el).addEventListener('submit', async (e) => { e.preventDefault(); const f = e.target; fieldErrors(f); try { await withBtn($('button[type=submit]', f), () => api.post(`/business/${D.business.id}/transactions`, { type, amount: f.amount.value, partnerId: f.partnerId?.value, category: f.category.value, note: f.note.value, date: f.date.value })); toast('Entry recorded', 'good'); m.close(); done(); } catch (err) { toast(err.message, 'bad'); } }); } });
}
function invitePartnerModal(D, done) {
  modal({ title: 'Invite a partner', body: `<form class="stack" id="f" novalidate><p class="muted" style="margin:0">They can have an Expensio account or not — we’ll email a secure link. They must verify their NID before joining.</p><div class="field"><label>Email</label><input class="input" type="email" name="email" required></div>
    <div class="form-grid two"><div class="field"><label>Role</label><select class="input" name="role"><option value="partner">Partner (can add entries)</option><option value="investor">Investor (view-only)</option><option value="accountant">Accountant (view-only)</option><option value="owner">Co-owner (full control)</option></select></div><div class="field"><label>Ownership share (%)</label><input class="input mono" name="own" inputmode="decimal" value="0"></div></div>
    <span class="hint">Shares come out of your own ownership so the total always equals 100%.</span>${btnHtml('Send invitation', 'btn-primary block lg', 'type="submit"')}</form>`,
  onMount: (m) => $('#f', m.el).addEventListener('submit', async (e) => { e.preventDefault(); const f = e.target; fieldErrors(f); try { await withBtn($('button[type=submit]', f), () => api.post(`/business/${D.business.id}/invite`, { email: f.email.value, role: f.role.value, ownershipPercent: Number(f.own.value) || 0 })); toast('Invitation sent ✉️', 'good'); m.close(); done(); } catch (err) { if (err.details) fieldErrors(f, err.details); else toast(err.message, 'bad'); } }) });
}
function editPartnerModal(D, p, done) {
  modal({ title: `Edit ${p.name}`, body: `<form class="stack" id="f"><div class="form-grid two"><div class="field"><label>Role</label><select class="input" name="role">${Object.entries(ROLES).map(([k, l]) => `<option value="${k}" ${p.role === k ? 'selected' : ''}>${l}</option>`).join('')}</select></div><div class="field"><label>Ownership (%)</label><input class="input mono" name="own" value="${p.ownershipPercent}"></div></div>${btnHtml('Save', 'btn-primary block', 'type="submit"')}<button type="button" class="btn btn-danger block" data-rm>Remove from business</button></form>`,
  onMount: (m) => { $('#f', m.el).addEventListener('submit', async (e) => { e.preventDefault(); const f = e.target; try { await withBtn($('button[type=submit]', f), () => api.patch(`/business/${D.business.id}/partners/${p.userId}`, { role: f.role.value, ownershipPercent: Number(f.own.value) })); toast('Updated', 'good'); m.close(); done(); } catch (err) { toast(err.message, 'bad'); } });
    $('[data-rm]', m.el).addEventListener('click', async () => { if (!(await confirmBox({ title: 'Remove partner?', text: `${p.name}’s share returns to an owner.`, ok: 'Remove', danger: true }))) return; try { await api.del(`/business/${D.business.id}/partners/${p.userId}`); m.close(); done(); } catch (err) { toast(err.message, 'bad'); } }); } });
}
