import { api, download } from '../core/api.js';
import { store } from '../core/store.js';
import { $, $$, on, icon, esc, toast, modal, confirmBox, withBtn, btnHtml, fieldErrors, ago, dateFmt, setTheme, theme, currencies, avatar, empty, confetti } from '../core/ui.js';
import { nav, signOut, refreshUser } from '../app.js';
import { nidFields, readNid } from './business.js';

const EMOJI = ['🙂', '🦊', '🐼', '🦁', '🐯', '🦄', '🐙', '🐳', '🦉', '🐸', '🚀', '🌟'];
const COLORS = ['#0E7C7B', '#6366f1', '#f59e0b', '#ec4899', '#10b981', '#3b82f6', '#ef4444', '#8b5cf6'];

export async function notifications() {
  let { notifications: list } = await api.get('/notifications');
  const row = (n) => `<div class="notif-item ${n.read ? '' : 'unread'}" data-id="${n.id}" data-link="${esc(n.link || '')}"><span class="cat-ico">${{ expense: '🧾', settlement: '💸', invite: '✉️', reminder: '⏰', kyc: '🪪', announcement: '📣' }[n.type] || '🔔'}</span><div class="grow"><b>${esc(n.title)}</b><div class="muted" style="font-size:.88rem">${esc(n.body || '')}</div><div class="faint" style="font-size:.76rem">${ago(n.createdAt)}</div></div>${n.read ? '' : '<i class="notif-dot" style="position:static"></i>'}</div>`;
  const html = `<div class="stack" style="gap:18px"><div class="row between wrap"><h2 style="margin:0">Notifications</h2><button class="btn btn-glass sm" id="all">Mark all read</button></div><div class="card" id="nl">${list.length ? list.map(row).join('') : empty('🔔', 'All quiet', 'Activity from your groups and businesses will appear here.')}</div></div>`;
  return { title: 'Notifications', html, mount(root) {
    $('#all', root).onclick = async () => { await api.post('/notifications/read-all'); store.unread = 0; list = list.map((n) => ({ ...n, read: true })); $('#nl', root).innerHTML = list.map(row).join(''); document.querySelectorAll('[data-unread],[data-unread-dot]').forEach((e) => { e.hidden = true; }); };
    on(root, 'click', '[data-id]', async (_e, el) => { api.post(`/notifications/${el.dataset.id}/read`).catch(() => {}); if (el.dataset.link) nav(el.dataset.link); });
  } };
}

export async function settings({ user, query }) {
  const [{ kyc }, { sessions }] = await Promise.all([api.get('/me/kyc'), api.get('/me/sessions')]);
  let u = user; let tab = query.tab || 'profile';
  const tabs = [['profile', 'user', 'Profile'], ['security', 'lock', 'Security'], ['identity', 'id', 'Identity'], ['notifications', 'bell', 'Alerts'], ['privacy', 'shield', 'Privacy & data']];
  const idBadge = (s) => ({ approved: 'good', pending: 'warn', rejected: 'bad' }[s] || '');
  const panes = {
    profile: () => `<form class="card stack" id="pf" novalidate><div class="row" style="gap:16px">${avatar(u, 'lg')}<div><b style="font-size:1.2rem">${esc(u.name)}</b><div class="muted">${esc(u.email)} ${u.emailVerified ? '<span class="badge good">verified</span>' : '<span class="badge warn">unverified</span>'}</div></div></div>
      <div class="field"><label>Avatar</label><div class="row wrap">${EMOJI.map((e) => `<button type="button" class="chip ${u.avatar.emoji === e ? 'on' : ''}" data-em="${e}" style="font-size:1.2rem;padding:5px 9px">${e}</button>`).join('')}</div><div class="row wrap" style="margin-top:6px">${COLORS.map((c) => `<button type="button" data-col="${c}" aria-label="colour" style="width:30px;height:30px;border-radius:50%;border:3px solid ${u.avatar.color === c ? 'var(--text)' : 'transparent'};background:${c};cursor:pointer"></button>`).join('')}</div></div>
      <div class="form-grid two"><div class="field"><label>Full name</label><input class="input" name="name" value="${esc(u.name)}"></div><div class="field"><label>Phone</label><input class="input" name="phone" value="${esc(u.phone || '')}"></div>
      <div class="field"><label>Mobile banking</label><select class="input" name="provider"><option value="">None</option>${['bKash', 'Nagad', 'Rocket', 'Upay', 'Bank', 'Other'].map((p) => `<option ${u.mobileBanking?.provider === p ? 'selected' : ''}>${p}</option>`).join('')}</select></div><div class="field"><label>Account number</label><input class="input" name="bnum" value="${esc(u.mobileBanking?.number || '')}"></div>
      <div class="field"><label>Default currency</label><select class="input" name="baseCurrency">${Object.keys(currencies()).map((c) => `<option ${u.baseCurrency === c ? 'selected' : ''}>${c}</option>`).join('')}</select></div><div class="field"><label>Theme</label><select class="input" name="theme"><option value="dark" ${theme() === 'dark' ? 'selected' : ''}>Dark</option><option value="light" ${theme() === 'light' ? 'selected' : ''}>Light</option></select></div></div>
      ${btnHtml('Save profile', 'btn-primary', 'type="submit"')}</form>`,
    security: () => `<div class="stack"><form class="card stack" id="pw" novalidate><h3 style="margin:0">Change password</h3><div class="form-grid two"><div class="field"><label>Current password</label><input class="input" type="password" name="currentPassword" autocomplete="current-password"></div><div class="field"><label>New password</label><input class="input" type="password" name="newPassword" autocomplete="new-password"></div></div>${btnHtml('Update password', 'btn-glass', 'type="submit"')}</form>
      <div class="card"><div class="row wrap"><span class="cat-ico">${icon('shield')}</span><div class="grow"><h3 style="margin:0">Two-factor sign-in</h3><div class="muted">Get a one-time email code every time you sign in. ${u.isStaff ? 'Mandatory for staff.' : 'Required to create a business.'}</div></div>${u.isStaff ? '<span class="badge good">Always on</span>' : u.twoFactorEnabled ? '<button class="btn btn-danger sm" id="2fa-off">Turn off</button>' : '<button class="btn btn-primary sm" id="2fa-on">Enable</button>'}</div></div>
      <div class="card"><div class="row between wrap"><h3 style="margin:0">Active sessions</h3><button class="btn btn-danger sm" id="logout-all">Sign out everywhere</button></div>${sessions.map((s) => `<div class="list-item"><span class="cat-ico">${icon('phone')}</span><div class="grow truncate"><b class="truncate">${esc((s.userAgent || 'Unknown device').slice(0, 70))}</b><div class="muted" style="font-size:.8rem">${esc(s.ip || '')} · active ${ago(s.lastUsedAt || s.createdAt)}</div></div>${s.current ? '<span class="badge good">This device</span>' : `<button class="btn btn-ghost sm" data-revoke="${s.id}">${icon('x')}</button>`}</div>`).join('')}</div></div>`,
    identity: () => `<div class="card stack"><div class="row wrap"><span class="cat-ico">${icon('id')}</span><div class="grow"><h3 style="margin:0">National ID verification</h3><div class="muted">Required for business owners and partners.</div></div>${kyc ? `<span class="badge ${idBadge(kyc.status)}">${kyc.status}</span>` : '<span class="badge">Not submitted</span>'}</div>
      ${kyc ? `<div class="secure-note">${icon('lock')}<span>On file: <b class="mono">${esc(kyc.masked)}</b> · ${esc(kyc.nameOnNid)} · submitted ${dateFmt(kyc.submittedAt)}${kyc.status === 'rejected' ? `<br><span class="money-neg">Rejected: ${esc(kyc.reason || '')}</span>` : ''}</span></div>` : ''}
      ${kyc?.status === 'approved' ? '<p class="muted" style="margin:0">Your identity is verified. Contact support to change it.</p>' : `<form class="stack" id="kf" novalidate>${nidFields()}${btnHtml(kyc ? 'Resubmit for review' : 'Submit for verification', 'btn-primary', 'type="submit"')}</form>`}</div>`,
    notifications: () => `<div class="card stack"><h3 style="margin:0">Email notifications</h3>${[['activity', 'New expenses & edits', 'When someone adds or changes an expense that involves you.'], ['settlements', 'Payments & reminders', 'Payment confirmations, declines and friendly nudges.'], ['invites', 'Invitations', 'Group and business invitations.'], ['marketing', 'Product news', 'Occasional updates from StratifyX Global.']].map(([k, t, d]) => `<div class="list-item"><div class="grow"><b>${t}</b><div class="muted" style="font-size:.85rem">${d}</div></div><label class="switch"><input type="checkbox" data-pref="${k}" ${u.notificationPrefs?.[k] ? 'checked' : ''}><span></span></label></div>`).join('')}<p class="faint" style="margin:0;font-size:.82rem">In-app notifications are always on. Security emails (codes, resets) can’t be disabled.</p></div>`,
    privacy: () => `<div class="stack"><div class="card"><div class="row wrap"><span class="cat-ico">${icon('download')}</span><div class="grow"><h3 style="margin:0">Download your data</h3><div class="muted">A JSON file with your profile, groups, expenses and settlements.</div></div><button class="btn btn-glass" id="export">Download</button></div></div>
      <div class="card"><div class="row wrap"><span class="cat-ico">${icon('trash')}</span><div class="grow"><h3 style="margin:0">Delete my account</h3><div class="muted">Sends a deletion request to our compliance team. Open balances and business obligations may need to be resolved first.</div></div><button class="btn btn-danger" id="del">Request deletion</button></div></div>
      <div class="card row wrap"><span class="grow muted">Read our <a href="#/privacy">Privacy Policy</a>, <a href="#/terms">Terms</a> and <a href="#/cookies">Cookie Policy</a>.</span><button class="btn btn-glass sm" data-logout>${icon('logout')} Sign out</button></div></div>`,
  };
  const html = `<div class="stack" style="gap:18px"><h2 style="margin:0">Settings</h2><div class="tabs" id="st">${tabs.map(([k, i, l]) => `<button class="tab ${tab === k ? 'on' : ''}" data-tab="${k}">${icon(i)}${l}</button>`).join('')}</div><div id="sb"></div></div>`;
  return { title: 'Settings', html, mount(root) {
    const paint = () => { $('#sb', root).innerHTML = panes[tab](); };
    paint();
    on(root, 'click', '[data-tab]', (_e, b) => { tab = b.dataset.tab; $$('#st .tab', root).forEach((t) => t.classList.toggle('on', t === b)); paint(); });
    let emoji = u.avatar.emoji; let color = u.avatar.color;
    on(root, 'click', '[data-em]', (_e, b) => { emoji = b.dataset.em; $$('[data-em]', root).forEach((x) => x.classList.toggle('on', x === b)); });
    on(root, 'click', '[data-col]', (_e, b) => { color = b.dataset.col; $$('[data-col]', root).forEach((x) => { x.style.borderColor = x === b ? 'var(--text)' : 'transparent'; }); });
    on(root, 'click', '[data-revoke]', async (_e, b) => { await api.del(`/me/sessions/${b.dataset.revoke}`); b.closest('.list-item').remove(); toast('Session ended', 'good'); });
    on(root, 'click', '#logout-all', async () => { if (await confirmBox({ title: 'Sign out everywhere?', text: 'All devices, including this one, will be signed out.', ok: 'Sign out all', danger: true })) { await api.post('/auth/logout-all'); signOut(true); } });
    on(root, 'click', '#export', () => download('/me/export', 'expensio-my-data.json').catch((e) => toast(e.message, 'bad')));
    on(root, 'click', '#del', async () => { if (await confirmBox({ title: 'Request account deletion?', text: 'Our team will contact you to complete this securely.', ok: 'Send request', danger: true })) { try { const d = await api.post('/me/delete-request', {}); toast(`Request sent (ref ${d.ref})`, 'good'); } catch (e) { toast(e.message, 'bad'); } } });
    on(root, 'click', '#2fa-on', async () => { try { await api.post('/me/2fa/request'); } catch (e) { return toast(e.message, 'bad'); }
      modal({ title: 'Enable two-factor', body: `<form class="stack" id="f"><p class="muted" style="margin:0">We emailed a 6-digit code to <b>${esc(u.email)}</b>.</p><div class="field"><input class="input mono" name="code" inputmode="numeric" maxlength="6" placeholder="••••••" style="text-align:center;font-size:1.6rem;letter-spacing:.5em"></div>${btnHtml('Confirm', 'btn-primary block', 'type="submit"')}</form>`, onMount: (m) => $('#f', m.el).addEventListener('submit', async (e) => { e.preventDefault(); try { const d = await api.post('/me/2fa/enable', { code: e.target.code.value }); u = d.user; store.user = d.user; m.close(); confetti(60); toast('Two-factor enabled 🔐', 'good'); paint(); } catch (err) { toast(err.message, 'bad'); } }) }); });
    on(root, 'click', '#2fa-off', () => modal({ title: 'Turn off two-factor', body: `<form class="stack" id="f"><div class="field"><label>Confirm your password</label><input class="input" type="password" name="password"></div>${btnHtml('Turn off', 'btn-danger block', 'type="submit"')}</form>`, onMount: (m) => $('#f', m.el).addEventListener('submit', async (e) => { e.preventDefault(); try { const d = await api.post('/me/2fa/disable', { password: e.target.password.value }); u = d.user; store.user = d.user; m.close(); toast('Two-factor disabled', 'info'); paint(); } catch (err) { toast(err.message, 'bad'); } }) }));
    root.addEventListener('change', async (e) => { const k = e.target.dataset.pref; if (!k) return; try { const d = await api.patch('/me', { notificationPrefs: { [k]: e.target.checked } }); u = d.user; store.user = d.user; toast('Preference saved', 'good', 1800); } catch (err) { toast(err.message, 'bad'); e.target.checked = !e.target.checked; } });
    root.addEventListener('submit', async (e) => { e.preventDefault(); const f = e.target; const btn = $('button[type=submit]', f); fieldErrors(f);
      try {
        if (f.id === 'pf') { setTheme(f.theme.value); const d = await withBtn(btn, () => api.patch('/me', { name: f.elements.name.value, phone: f.phone.value, mobileBanking: { provider: f.provider.value, number: f.bnum.value }, avatar: { emoji, color }, baseCurrency: f.baseCurrency.value })); u = d.user; store.user = d.user; toast('Profile saved ✅', 'good'); }
        if (f.id === 'pw') { const d = await withBtn(btn, () => api.post('/me/change-password', { currentPassword: f.currentPassword.value, newPassword: f.newPassword.value })); const { setSession } = await import('../app.js'); const { user: me } = await api.get('/me'); setSession({ accessToken: d.accessToken, user: me }); f.reset(); toast('Password updated. Other devices were signed out.', 'good'); }
        if (f.id === 'kf') { const d = await withBtn(btn, () => api.post('/me/kyc', readNid(f))); Object.assign(kyc || {}, d.kyc); toast('Submitted for review 🪪', 'good'); nav('/settings?tab=identity'); location.reload(); }
      } catch (err) { if (err.details) fieldErrors(f, err.details); toast(err.message, 'bad'); } });
  } };
}
