// Staff-only operations panel. Loaded lazily – never shipped to customer sessions.
import { api } from '../core/api.js';
import { $, $$, on, icon, esc, money, dateFmt, ago, toast, modal, confirmBox, withBtn, btnHtml, empty, animateNumbers } from '../core/ui.js';
import { md } from '../pages/info.js';

const MODS = [['overview', 'chart', 'Overview', 'overview'], ['users', 'users', 'Users', 'users'], ['kyc', 'id', 'KYC / NID', 'kyc'], ['businesses', 'briefcase', 'Businesses', 'businesses'], ['tickets', 'help', 'Support', 'tickets'], ['content', 'file', 'Content', 'content'], ['flags', 'zap', 'Flags & config', 'flags'], ['audit', 'shield', 'Audit log', 'audit'], ['health', 'refresh', 'System health', 'health']];
const ROLE_LABEL = { super_admin: 'Super Admin', kyc_reviewer: 'KYC Reviewer', support: 'Support Agent', content_editor: 'Content Editor', user: 'Customer' };
const can = (perms, mod) => perms.includes('*') || perms.includes(mod);

export default async function admin({ params }) {
  const me = await api.get('/admin/me'); const mods = MODS.filter((m) => can(me.perms, m[3]));
  const sec = params.section && mods.some((m) => m[0] === params.section) ? params.section : mods[0][0];
  const html = `<div class="stack" style="gap:18px"><div class="row between wrap"><div><h2 style="margin:0">Admin panel</h2><span class="badge warn">${ROLE_LABEL[me.role]}</span> <span class="faint" style="font-size:.82rem">All actions are audit-logged.</span></div></div>
    <div class="tabs">${mods.map(([k, i, l]) => `<a class="tab ${sec === k ? 'on' : ''}" href="#/admin/${k}" style="text-decoration:none">${icon(i)}${l}</a>`).join('')}</div><div id="ad"><div class="skeleton" style="height:220px"></div></div></div>`;
  return { title: 'Admin', html, async mount(root) { const box = $('#ad', root); try { await SECTIONS[sec](box, me); animateNumbers(root); } catch (e) { box.innerHTML = `<div class="card">${empty('🚫', 'Unavailable', e.message)}</div>`; } } };
}

const SECTIONS = {
  async overview(box) {
    const { kpis: k, signups } = await api.get('/admin/overview'); const max = Math.max(...signups.map((s) => s.n), 1);
    const tile = (l, v, c = '') => `<div class="card kpi"><span class="l">${l}</span><b class="v ${c}" data-count="${v}">0</b></div>`;
    box.innerHTML = `<div class="stack"><div class="grid g4">${tile('Users', k.users)}${tile('New today', k.newToday)}${tile('Active (7d)', k.active7)}${tile('Verified rate %', k.verifiedRate, 'money-pos')}${tile('Groups', k.groups)}${tile('Expenses', k.expenses)}${tile('Businesses', k.businesses)}${tile('Pending KYC', k.kycPending, k.kycPending ? 'money-neg' : '')}${tile('Open tickets', k.ticketsOpen, k.ticketsOpen ? 'money-neg' : '')}${tile('Flagged', k.flagged)}</div>
      <div class="grid g2"><div class="card"><h3>Expense volume</h3>${k.volume.map((v) => `<div class="list-item"><b class="grow">${esc(v.currency || '—')}</b><b class="mono">${money(v.totalMinor, v.currency || 'BDT')}</b></div>`).join('') || '<p class="muted">No data yet.</p>'}</div>
      <div class="card"><h3>Signups · 14 days</h3><div class="bars" style="height:120px">${signups.map((s) => `<div class="bar"><span>${s.n}</span><i style="height:${Math.max(6, (s.n / max) * 100)}%"></i><span>${s._id.slice(8)}</span></div>`).join('') || '<p class="muted">No signups yet.</p>'}</div></div></div></div>`;
  },
  async users(box, me) {
    let q = ''; let page = 1;
    const load = async () => { const d = await api.get(`/admin/users?q=${encodeURIComponent(q)}&page=${page}`);
      $('#ul', box).innerHTML = `<div class="table-wrap"><table class="t"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Last login</th><th></th></tr></thead><tbody>${d.users.map((u) => `<tr><td><b>${esc(u.name)}</b><div class="muted" style="font-size:.8rem">${esc(u.email)} ${u.emailVerified ? '' : '<span class="badge warn">unverified</span>'}</div></td><td><span class="badge ${u.role === 'user' ? '' : 'info'}">${ROLE_LABEL[u.role]}</span></td><td><span class="badge ${u.status === 'active' ? 'good' : 'bad'}">${u.status}</span></td><td class="muted">${u.lastLoginAt ? ago(u.lastLoginAt) : '—'}</td><td><button class="btn btn-glass sm" data-u="${u.id}">Manage</button></td></tr>`).join('')}</tbody></table></div><div class="row between" style="margin-top:12px"><span class="muted">${d.total} users</span><div class="row"><button class="btn btn-glass sm" data-p="-1" ${page <= 1 ? 'disabled' : ''}>Prev</button><button class="btn btn-glass sm" data-p="1" ${page >= d.pages ? 'disabled' : ''}>Next</button></div></div>`; };
    box.innerHTML = `<div class="card"><input class="input" id="uq" placeholder="Search name or email…" style="margin-bottom:14px"><div id="ul"></div></div>`; await load();
    let t; $('#uq', box).addEventListener('input', (e) => { clearTimeout(t); t = setTimeout(() => { q = e.target.value; page = 1; load(); }, 300); });
    on(box, 'click', '[data-p]', (_e, b) => { page += Number(b.dataset.p); load(); });
    on(box, 'click', '[data-u]', async (_e, b) => { const { user: u, groups, sessions, kyc, activity } = await api.get(`/admin/users/${b.dataset.u}`); const su = me.role === 'super_admin';
      modal({ title: u.name, body: `<div class="stack"><div class="muted">${esc(u.email)} · joined ${dateFmt(u.createdAt)}</div><div class="grid g3" style="gap:10px"><div class="card tight kpi"><span class="l">Groups</span><b class="v">${groups}</b></div><div class="card tight kpi"><span class="l">Sessions</span><b class="v">${sessions}</b></div><div class="card tight kpi"><span class="l">NID</span><b>${kyc ? kyc.status : 'none'}</b></div></div>
        ${su ? `<div class="form-grid two"><div class="field"><label>Role</label><select class="input" id="r">${Object.entries(ROLE_LABEL).map(([k, l]) => `<option value="${k}" ${u.role === k ? 'selected' : ''}>${l}</option>`).join('')}</select></div><div class="field"><label>Status</label><select class="input" id="s"><option ${u.status === 'active' ? 'selected' : ''}>active</option><option ${u.status === 'disabled' ? 'selected' : ''}>disabled</option></select></div></div><div class="row wrap">${btnHtml('Save', 'btn-primary', 'data-save')}<button class="btn btn-danger" data-fl>Force logout</button></div>` : '<p class="muted">Read-only for your role.</p>'}
        <div class="lbl">RECENT ACTIVITY</div>${activity.map((a) => `<div class="muted" style="font-size:.82rem">${esc(a.action)} · ${ago(a.createdAt)} · ${esc(a.ip || '')}</div>`).join('') || '<span class="muted">None</span>'}</div>`,
      onMount: (m) => { m.el.querySelector('[data-save]')?.addEventListener('click', async (e) => { try { await withBtn(e.currentTarget, () => api.patch(`/admin/users/${u.id}`, { role: $('#r', m.el).value, status: $('#s', m.el).value })); toast('Updated', 'good'); m.close(); load(); } catch (err) { toast(err.message, 'bad'); } });
        m.el.querySelector('[data-fl]')?.addEventListener('click', async () => { await api.post(`/admin/users/${u.id}/force-logout`); toast('User signed out everywhere', 'good'); }); } }); });
  },
  async kyc(box) {
    let status = 'pending';
    const load = async () => { const { items } = await api.get(`/admin/kyc?status=${status}`);
      $('#kl', box).innerHTML = items.length ? items.map((n) => `<div class="card" style="margin-bottom:12px"><div class="row wrap"><span class="cat-ico">${icon('id')}</span><div class="grow"><b>${esc(n.user?.name)}</b> <span class="muted">${esc(n.user?.email)}</span><div class="muted" style="font-size:.85rem">NID <span class="mono">${esc(n.masked)}</span> · name on NID: <b>${esc(n.nameOnNid)}</b> ${n.nameMatches ? '<span class="badge good">name matches</span>' : '<span class="badge warn">name differs</span>'} · DOB ${dateFmt(n.dob)} · waiting ${ago(n.submittedAt)}</div>${n.fatherName ? `<div class="faint" style="font-size:.8rem">Father: ${esc(n.fatherName)} ${n.address ? `· ${esc(n.address)}` : ''}</div>` : ''}${n.reason ? `<div class="money-neg" style="font-size:.82rem">Reason: ${esc(n.reason)}</div>` : ''}</div>
        ${status === 'pending' ? `<button class="btn btn-glass sm" data-reveal="${n.id}">${icon('eye')} Reveal</button><button class="btn btn-good sm" data-ok="${n.id}">Approve</button><button class="btn btn-danger sm" data-no="${n.id}">Reject</button>` : `<span class="badge ${n.status === 'approved' ? 'good' : 'bad'}">${n.status}</span>`}</div></div>`).join('') : empty('🪪', 'Queue is empty', 'No submissions in this state.'); };
    box.innerHTML = `<div class="stack"><div class="pill-tabs">${['pending', 'approved', 'rejected'].map((s) => `<button class="chip ${s === status ? 'on' : ''}" data-s="${s}">${s}</button>`).join('')}</div><div id="kl"></div></div>`; await load();
    on(box, 'click', '[data-s]', (_e, b) => { status = b.dataset.s; $$('[data-s]', box).forEach((c) => c.classList.toggle('on', c === b)); load(); });
    on(box, 'click', '[data-ok]', async (_e, b) => { try { await api.post(`/admin/kyc/${b.dataset.ok}/decision`, { decision: 'approve' }); toast('Approved ✅', 'good'); load(); } catch (e) { toast(e.message, 'bad'); } });
    on(box, 'click', '[data-no]', (_e, b) => modal({ title: 'Reject submission', body: `<form class="stack" id="f"><div class="field"><label>Reason (sent to the user)</label><input class="input" name="reason" required minlength="5"></div>${btnHtml('Reject', 'btn-danger block', 'type="submit"')}</form>`, onMount: (m) => $('#f', m.el).addEventListener('submit', async (e) => { e.preventDefault(); try { await api.post(`/admin/kyc/${b.dataset.no}/decision`, { decision: 'reject', reason: e.target.reason.value }); m.close(); toast('Rejected', 'good'); load(); } catch (err) { toast(err.message, 'bad'); } }) }));
    on(box, 'click', '[data-reveal]', (_e, b) => modal({ title: 'Re-authenticate to reveal', body: `<form class="stack" id="f"><p class="muted" style="margin:0">Revealing a full NID is logged in the audit trail.</p><div class="field"><label>Your password</label><input class="input" type="password" name="password"></div>${btnHtml('Reveal', 'btn-primary block', 'type="submit"')}</form><div id="out"></div>`, onMount: (m) => $('#f', m.el).addEventListener('submit', async (e) => { e.preventDefault(); try { const d = await api.post(`/admin/kyc/${b.dataset.reveal}/reveal`, { password: e.target.password.value }); $('#out', m.el).innerHTML = `<div class="secure-note" style="margin-top:12px">${icon('lock')}<b class="mono" style="font-size:1.3rem">${esc(d.nidNumber)}</b></div>`; e.target.remove(); } catch (err) { toast(err.message, 'bad'); } }) }));
  },
  async businesses(box, me) {
    const { businesses } = await api.get('/admin/businesses');
    box.innerHTML = `<div class="card"><div class="table-wrap"><table class="t"><thead><tr><th>Business</th><th>Type</th><th>Partners</th><th>Status</th><th></th></tr></thead><tbody>${businesses.map((b) => `<tr><td><b>${esc(b.name)}</b><div class="faint" style="font-size:.78rem">${dateFmt(b.createdAt)}</div></td><td>${esc(b.type)}</td><td>${b.partners}</td><td><span class="badge ${b.status === 'flagged' ? 'bad' : 'good'}">${b.status}</span></td><td><button class="btn btn-glass sm" data-b="${b.id}">Inspect</button></td></tr>`).join('')}</tbody></table></div></div>`;
    on(box, 'click', '[data-b]', async (_e, b) => { const d = await api.get(`/admin/businesses/${b.dataset.b}`); const su = me.role === 'super_admin';
      modal({ title: d.business.name, lg: true, body: `<div class="stack"><div class="muted">${esc(d.business.type)} · ${d.business.currency}${d.business.tradeLicense ? ` · licence ${esc(d.business.tradeLicense)}` : ''}</div>${d.partners.map((p) => `<div class="list-item"><div class="grow"><b>${esc(p.name)}</b> <span class="muted">${esc(p.email)}</span></div><span class="badge">${p.role} · ${p.ownershipPercent}%</span><span class="badge ${p.identity === 'approved' ? 'good' : p.identity === 'pending' ? 'warn' : 'bad'}">NID ${p.identity}</span></div>`).join('')}
        <div class="grid g4" style="gap:10px">${['investment', 'profit', 'expense', 'withdrawal'].map((k) => `<div class="card tight kpi"><span class="l">${k}</span><b class="mono">${money(d.summary[k], d.business.currency, { compact: true })}</b></div>`).join('')}</div>
        ${su ? `<div class="field"><label>${d.business.status === 'flagged' ? 'Clear flag' : 'Flag for review'} — reason</label><input class="input" id="fr" value="${esc(d.business.flagReason || '')}"></div><button class="btn ${d.business.status === 'flagged' ? 'btn-good' : 'btn-danger'}" data-flag>${d.business.status === 'flagged' ? 'Unflag business' : 'Flag business'}</button>` : ''}
        <div class="lbl">RECENT EVENTS</div>${d.events.map((e) => `<div class="muted" style="font-size:.82rem">${esc(e.action)} · ${esc(e.actorEmail || '')} · ${ago(e.createdAt)}</div>`).join('')}</div>`,
      onMount: (m) => m.el.querySelector('[data-flag]')?.addEventListener('click', async () => { await api.post(`/admin/businesses/${d.business.id}/flag`, { flagged: d.business.status !== 'flagged', reason: $('#fr', m.el).value }); toast('Updated', 'good'); m.close(); SECTIONS.businesses(box, me); }) }); });
  },
  async tickets(box) {
    let status = '';
    const load = async () => { const { tickets } = await api.get(`/admin/tickets?status=${status}`);
      $('#tl', box).innerHTML = tickets.length ? tickets.map((t) => `<div class="card" style="margin-bottom:12px"><div class="row between wrap"><div><b>${esc(t.subject)}</b> <span class="mono faint">#${esc(t.ref)}</span><div class="muted" style="font-size:.82rem">${esc(t.name)} · ${esc(t.email)} · ${esc(t.category)} · ${ago(t.updatedAt)}</div></div><span class="badge ${t.status === 'resolved' ? 'good' : t.status === 'pending' ? 'info' : 'warn'}">${t.status}</span></div>
        <div class="stack-sm" style="margin:12px 0">${t.messages.map((m) => `<div class="card tight flat" style="${m.from === 'staff' ? 'border-color:var(--primary)' : ''}"><div class="faint" style="font-size:.74rem;font-weight:700">${esc(m.author)} · ${ago(m.at)}</div><div style="white-space:pre-wrap">${esc(m.body)}</div></div>`).join('')}</div>
        <form class="row wrap" data-r="${t.id}"><input class="input grow" name="message" placeholder="Reply to customer…"><button class="btn btn-primary" type="submit">${icon('send')}</button><button type="button" class="btn btn-good" data-resolve="${t.id}">Resolve</button></form></div>`).join('') : empty('🎧', 'Inbox zero', 'No tickets match.'); };
    box.innerHTML = `<div class="stack"><div class="pill-tabs">${['', 'open', 'pending', 'resolved'].map((s) => `<button class="chip ${s === status ? 'on' : ''}" data-s="${s}">${s || 'all'}</button>`).join('')}</div><div id="tl"></div></div>`; await load();
    on(box, 'click', '[data-s]', (_e, b) => { status = b.dataset.s; $$('[data-s]', box).forEach((c) => c.classList.toggle('on', c === b)); load(); });
    on(box, 'click', '[data-resolve]', async (_e, b) => { await api.post(`/admin/tickets/${b.dataset.resolve}/reply`, { status: 'resolved' }); toast('Resolved', 'good'); load(); });
    box.addEventListener('submit', async (e) => { const id = e.target.dataset.r; if (!id) return; e.preventDefault(); const message = e.target.message.value.trim(); if (!message) return; try { await api.post(`/admin/tickets/${id}/reply`, { message, assignToMe: true }); toast('Reply sent & emailed', 'good'); load(); } catch (err) { toast(err.message, 'bad'); } });
  },
  async content(box) {
    const { pages } = await api.get('/admin/content');
    box.innerHTML = `<div class="grid g2">${pages.map((p) => `<div class="card"><div class="row between"><div><b>${esc(p.title)}</b><div class="muted" style="font-size:.82rem">/${p.slug} · v${p.version} · ${ago(p.updatedAt)}</div></div><button class="btn btn-glass sm" data-e="${p.slug}">${icon('edit')} Edit</button></div></div>`).join('')}</div>`;
    on(box, 'click', '[data-e]', (_e, b) => { const p = pages.find((x) => x.slug === b.dataset.e);
      modal({ title: `Edit: ${p.title}`, lg: true, body: `<form class="stack" id="f"><div class="field"><label>Title</label><input class="input" name="title" value="${esc(p.title)}"></div><div class="field"><label>Body (Markdown: # ## - **bold** _italic_ [text](#/link))</label><textarea class="input mono" name="body" style="min-height:300px;font-size:.88rem">${esc(p.body)}</textarea></div><div class="row wrap">${btnHtml('Publish new version', 'btn-primary', 'type="submit"')}<button type="button" class="btn btn-glass" data-prev>Preview</button></div><div id="pv" class="card flat legal" style="display:none"></div></form>`,
        onMount: (m) => { m.el.querySelector('[data-prev]').onclick = () => { const pv = $('#pv', m.el); pv.style.display = 'block'; pv.innerHTML = md($('[name=body]', m.el).value); };
          $('#f', m.el).addEventListener('submit', async (e) => { e.preventDefault(); try { await withBtn($('button[type=submit]', e.target), () => api.put(`/admin/content/${p.slug}`, { title: e.target.title.value, body: e.target.body.value })); toast('Published', 'good'); m.close(); SECTIONS.content(box); } catch (err) { toast(err.message, 'bad'); } }); } }); });
  },
  async flags(box) {
    const [{ flags }, cfg] = await Promise.all([api.get('/admin/flags'), api.get('/config')]);
    box.innerHTML = `<div class="stack"><div class="card"><h3>Feature flags</h3>${flags.map((f) => `<div class="list-item"><div class="grow"><b>${esc(f.key)}</b><div class="muted" style="font-size:.85rem">${esc(f.description || '')}</div></div><label class="switch"><input type="checkbox" data-flag="${f.key}" ${f.enabled ? 'checked' : ''}><span></span></label></div>`).join('')}</div>
      <div class="card stack"><h3 style="margin:0">Maintenance & banner</h3><div class="list-item" style="border:0"><div class="grow"><b>Maintenance mode</b><div class="muted" style="font-size:.85rem">Blocks all customer API calls (staff & sign-in stay available).</div></div><label class="switch"><input type="checkbox" id="mt" ${cfg.maintenance ? 'checked' : ''}><span></span></label></div><div class="field"><label>Announcement banner (shown on every page)</label><div class="input-group"><input class="input grow" id="bn" maxlength="240" value="${esc(cfg.banner)}"><button class="btn btn-glass" id="bs">Save</button></div></div></div>
      <div class="card stack"><h3 style="margin:0">Broadcast to all users</h3><div class="field"><label>Title</label><input class="input" id="bt" maxlength="100"></div><div class="field"><label>Message</label><input class="input" id="bm" maxlength="400"></div><button class="btn btn-primary" id="bb">${icon('send')} Send in-app notification</button></div></div>`;
    box.addEventListener('change', async (e) => { try { if (e.target.dataset.flag) await api.put(`/admin/flags/${e.target.dataset.flag}`, { enabled: e.target.checked }); if (e.target.id === 'mt') await api.put('/admin/settings', { maintenance: e.target.checked }); toast('Saved', 'good', 1800); } catch (err) { toast(err.message, 'bad'); e.target.checked = !e.target.checked; } });
    $('#bs', box).onclick = async () => { await api.put('/admin/settings', { banner: $('#bn', box).value }); toast('Banner saved', 'good'); };
    $('#bb', box).onclick = async () => { if (!(await confirmBox({ title: 'Send to every user?', text: 'This creates a notification for all active accounts.', ok: 'Send' }))) return; try { const d = await api.post('/admin/broadcast', { title: $('#bt', box).value, body: $('#bm', box).value }); toast(`Sent to ${d.recipients} users`, 'good'); } catch (e) { toast(e.message, 'bad'); } };
  },
  async audit(box) {
    let page = 1; let action = '';
    const load = async () => { const d = await api.get(`/admin/audit?page=${page}&action=${encodeURIComponent(action)}`);
      $('#al', box).innerHTML = `<div class="table-wrap"><table class="t"><thead><tr><th>When</th><th>Actor</th><th>Action</th><th>Entity</th><th>Change</th></tr></thead><tbody>${d.events.map((e) => `<tr><td class="muted nowrap">${dateFmt(e.at, { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })}</td><td>${esc(e.actor || e.actorType)}<div class="faint" style="font-size:.74rem">${esc(e.ip || '')}</div></td><td><b>${esc(e.action)}</b></td><td class="muted mono" style="font-size:.78rem">${esc(e.entity)}</td><td class="mono faint" style="font-size:.74rem;max-width:260px;overflow:hidden;text-overflow:ellipsis">${esc(JSON.stringify(e.after || e.before || ''))}</td></tr>`).join('')}</tbody></table></div><div class="row between" style="margin-top:12px"><span class="muted">${d.total} events</span><div class="row"><button class="btn btn-glass sm" data-p="-1" ${page <= 1 ? 'disabled' : ''}>Prev</button><button class="btn btn-glass sm" data-p="1" ${page >= d.pages ? 'disabled' : ''}>Next</button></div></div>`; };
    box.innerHTML = `<div class="card"><input class="input" id="af" placeholder="Filter by action prefix e.g. kyc. / admin. / business." style="margin-bottom:14px"><div id="al"></div></div>`; await load();
    let t; $('#af', box).addEventListener('input', (e) => { clearTimeout(t); t = setTimeout(() => { action = e.target.value; page = 1; load(); }, 300); });
    on(box, 'click', '[data-p]', (_e, b) => { page += Number(b.dataset.p); load(); });
  },
  async health(box) {
    const d = await api.get('/admin/health'); const dot = (ok) => `<span class="badge ${ok ? 'good' : 'bad'}">${ok ? 'Operational' : 'Down'}</span>`;
    box.innerHTML = `<div class="grid g2"><div class="card"><div class="row between"><h3 style="margin:0">API</h3>${dot(d.api.ok)}</div><p class="muted">Uptime ${Math.floor(d.api.uptimeSec / 3600)}h ${Math.floor((d.api.uptimeSec % 3600) / 60)}m · ${d.api.node} · ${d.api.memoryMb} MB</p></div>
      <div class="card"><div class="row between"><h3 style="margin:0">Database</h3>${dot(d.database.ok)}</div><p class="muted">MongoDB ping ${d.database.latencyMs} ms</p></div>
      <div class="card"><div class="row between"><h3 style="margin:0">Email</h3>${dot(d.email.ok)}</div><p class="muted">Mode: ${esc(d.email.mode)}${d.email.error ? ` · ${esc(d.email.error)}` : ''}</p></div>
      <div class="card"><div class="row between"><h3 style="margin:0">Background jobs</h3>${dot(d.jobs.recurringDue < 5)}</div><p class="muted">${d.jobs.recurringActive} recurring rules · ${d.jobs.recurringDue} due</p></div></div>`;
  },
};
